name: madrid_warrior
description: Madrid Warrior - Real Madrid Fan Community App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  facebook_flutter_sdk: ^18.0.0
  flutter_facebook_sdk: ^5.0.0
  webview_flutter: ^4.2.0
  sqflite: ^2.3.0
  path: ^1.8.0
  intl: ^0.19.0
  url_launcher: ^6.1.0
  firebase_core: ^2.20.0
  firebase_messaging: ^14.6.0
  flutter_local_notifications: ^16.0.0
  image_picker: ^1.0.0
  permission_handler: ^11.4.0
  material_design_icons_flutter: ^7.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
